artifacts_root: 'artifacts'

data_ingestion:
  data_root_dir: 'artifacts/data_ingestion'

data_validation:
  # paths
  data_root_dir: 'artifacts/data_validation'
  # inputs
  data_mnist_dir: 'artifacts/data_ingestion/MNIST/raw'
  # outputs
  STATUS_FILE: 'artifacts/data_validation/status.txt'

data_transformation:
  # paths
  data_root_dir: 'artifacts/data_transformation'
  # inputs
  data_mnist_dir: 'artifacts/data_ingestion'
  # outputs
  data_preprocessed_train_file: 'artifacts/data_transformation/train_loader.pth'
  data_preprocessed_val_file: 'artifacts/data_transformation/val_loader.pth'
  data_preprocessed_test_file: 'artifacts/data_transformation/test_loader.pth'
  # parameters
  data_train_size: 0.8
  data_val_size: 0.2
  data_random_state: 42
  data_batch_size: 64
  data_shuffle: True
